import Navigation from '@/components/Navigation'
import './globals.css'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Users app',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className='bg-[#edf2f7]'>
        <Navigation />
        <main className='relative flex flex-col max-w-4xl min-h-[101vh] gap-4 py-6 m-auto px-3 sm:px-0 '>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
